<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EightyNailz</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Description>Library for working with Windows Special Folders</Description>
    <Title>Library for working with Windows Special Folders</Title>
    <Version>0.0.1</Version>
    <Authors>Neil Saunders</Authors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

</Project>
